name: Merge Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      #   - name: Checkout repo
      #     uses: actions/checkout@v2
      #     with:
      #       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      #       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Merge files
        run: |
          echo "Merging files..."
          cat file*.txt > merged.txt

      #   - name: Commit & Push changes
      #     uses: actions-js/push@master
      #     with:
      #       github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Commit and push
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.error(1);
            const fs = require('fs');
            // const github = require('@actions/github');
            // const core = require('@actions/core');
            console.error(2);
            const path = 'merged.txt';
            const content = fs.readFileSync(path, 'utf8');
            const message = 'Merged files';
            console.error(3);
            const branch = github.context.ref.replace('refs/heads/', '');
            const owner = github.context.repo.owner;
            const repo = github.context.repo.repo;

            console.error(Committing "${message}" to ${owner}/${repo} on branch ${branch});
            github.getOctokit(core.getInput('github-token')).repos.createOrUpdateFileContents({
              owner,
              repo,
              path,
              message,
              content: Buffer.from(content).toString('base64'),
              branch
            });
