name: Merge Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Merge files
        run: |
          echo "Merging files..."
          cat file*.txt > merged.txt

      - name: Extract branch
        uses: actions/github-script@v5
        id: branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            return context.ref.replace('refs/heads/', '');

      - name: Commit and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "Staging"
          git add merged.txt
          echo "Committing"
          git commit -m "Merged files"
          echo "Pushing"
          git push origin ${{steps.branch.outputs.result}}
          echo "All done"
